import os
import logging
from telegram import Update, KeyboardButton, ReplyKeyboardMarkup, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, CallbackQueryHandler, filters, ContextTypes

# Enable logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

# Fetch Token
TOKEN = os.getenv("BOT_TOKEN")

def get_main_menu():
    """Generates the persistent bottom keyboard layout."""
    keyboard = [
        [KeyboardButton("📊 DASHBOARD")],
        [KeyboardButton("💳 PAYMENT"), KeyboardButton("⚡ FEATURES"), KeyboardButton("⚙️ SYSTEM")],
        [KeyboardButton("🖋️ SUBSCRIPTION"), KeyboardButton("🔑 ACTIVATE")],
        [KeyboardButton("❓ FAQ"), KeyboardButton("📈 RESULTS"), KeyboardButton("📋 COMMANDS")],
        [KeyboardButton("👤 PROFILE"), KeyboardButton("💬 SUPPORT"), KeyboardButton("🤝 PARTNER")]
    ]
    return ReplyKeyboardMarkup(keyboard, resize_keyboard=True, persistent=True)

def get_faq_text():
    """Returns the main FAQ text."""
    return (
        "❓ **UTILITY PANEL | FAQ**\n"
        "➖➖➖➖➖➖➖➖➖➖\n\n"
        "❓ **WHAT IS THIS BOT?**\n"
        "├ A premium utility solution for managing automated tasks.\n"
        "├ Navigate using the control panel below.\n\n"
        "➖➖➖➖➖➖➖➖➖➖"
    )

def get_faq_keyboard():
    """Returns the main FAQ inline keyboard."""
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("❓ ASK A QUESTION", callback_data="faq_ask")],
        [InlineKeyboardButton("← MENU", callback_data="faq_menu")]
    ])

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Sends the welcome message and activates the bottom keyboard."""
    user_name = update.effective_user.first_name
    
    welcome_text = (
        f"👋 **WELCOME TO UTILITY PANEL**\n"
        f"➖➖➖➖➖➖➖➖➖➖\n\n"
        f"🧠 **SYSTEM STATUS**\n"
        f"├ 🟢 **STATUS:** Operational\n"
        f"└ 📈 **UPTIME:** 100%\n\n"
        f"⚡ **WELCOME, {user_name}**\n"
        f"🛡️ **PREMIUM UTILITY SOLUTION**\n\n"
        f"👇 **TO GET STARTED, USE THE MENU BELOW**"
    )

    await update.message.reply_text(
        welcome_text, 
        reply_markup=get_main_menu(), 
        parse_mode="Markdown"
    )

async def handle_menu_clicks(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handles the text inputs generated by pressing the bottom keyboard buttons."""
    text = update.message.text

    if text == "📊 DASHBOARD":
        msg = (
            "📊 **UTILITY DASHBOARD**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "⛔ **ACCESS DENIED**\n"
            "├ 💳 **NO ACTIVE SUBSCRIPTION**\n"
            "└ 🛒 **PURCHASE A PLAN TO CONTINUE**\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        markup = InlineKeyboardMarkup([[InlineKeyboardButton("💳 PAYMENT", callback_data="trigger_payment")]])
        await update.message.reply_text(msg, reply_markup=markup, parse_mode="Markdown")

    elif text == "⚡ FEATURES":
        msg = (
            "⚡ **FEATURES**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "🧠 **SYSTEM STATUS**\n"
            "├ 🟢 **STATUS:** Operational\n"
            "└ 📈 **UPTIME:** 100%\n\n"
            "💬 **OUR UTILITY BOT IS PACKED WITH ADVANCED FEATURES!**"
        )
        await update.message.reply_text(msg, parse_mode="Markdown")

    elif text == "⚙️ SYSTEM":
        msg = (
            "⚙️ **SYSTEM STATUS**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "🖥️ **SERVER STATUS**\n"
            "├ ✅ **API:** Online\n"
            "├ ✅ **DATABASE:** Connected\n"
            "├ ✅ **SERVICES:** Operational\n"
            "└ ✅ **PAYMENTS:** Active\n\n"
            "📊 **PERFORMANCE**\n"
            "├ 📶 **UPTIME:** 99.9%\n"
            "├ ⚡ **RESPONSE:** < 100ms\n"
            "└ 🔄 **LAST CHECK:** Just now\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        await update.message.reply_text(msg, parse_mode="Markdown")

    elif text == "📈 RESULTS":
        msg = (
            "📈 **RESULTS**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "⭐ **REVIEWS & PERFORMANCE**\n"
            "├ • AUTHENTIC USER REVIEWS\n"
            "├ • SUCCESS STORIES\n"
            "├ • PERFORMANCE STATISTICS\n"
            "├ • COMMUNITY DISCUSSIONS\n"
            "└ • LATEST UPDATES\n\n"
            "🌐 **JOIN OUR COMMUNITY**\n"
            "👇 **CLICK BELOW**\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        markup = InlineKeyboardMarkup([[InlineKeyboardButton("VIEW RESULTS ↗", url="https://github.com")]])
        await update.message.reply_text(msg, reply_markup=markup, parse_mode="Markdown")

    elif text == "📋 COMMANDS":
        msg = (
            "📋 **COMMANDS**\n"
            "🟢 **OPERATIONAL | 📈 UPTIME: 100%**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "🤖 **MAIN COMMANDS**\n"
            "◆ 📓 /help | **VIEW COMMAND LIST**\n"
            "◆ 🛒 /purchase | **PURCHASE ACCESS**"
        )
        await update.message.reply_text(msg, parse_mode="Markdown")

    elif text == "💬 SUPPORT":
        msg = (
            "💬 **SUPPORT**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "📡 **SUPPORT STATUS**\n"
            "├ 🟢 **STATUS:** Active\n"
            "└ ⏱️ **RESPONSE:** 2-6h\n\n"
            "💬 **COMMON TOPICS**\n"
            "├ • PAYMENT PROCESSING\n"
            "├ • SUBSCRIPTION ACTIVATION\n"
            "├ • BOT SUPPORT\n"
            "└ • TECHNICAL ISSUES\n\n"
            "ℹ️ **BEFORE CONTACTING**\n"
            "├ • CHECK TRANSACTION STATUS\n"
            "├ • VERIFY SUBSCRIPTION\n"
            "├ • TRY /start COMMAND\n"
            "└ • REVIEW FAQ SECTION\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        markup = InlineKeyboardMarkup([
            [
                InlineKeyboardButton("💬 SUPPORT ↗", url="https://t.me/telegram"), 
                InlineKeyboardButton("📢 CHANNEL ↗", url="https://t.me/telegram")
            ]
        ])
        await update.message.reply_text(msg, reply_markup=markup, parse_mode="Markdown")

    elif text == "🤝 PARTNER":
        bot_username = context.bot.username if context.bot.username else "UtilityBot"
        msg = (
            "🤝 **PARTNER PANEL**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "🔗 **YOUR REFERRAL LINK:**\n"
            f"`https://t.me/{bot_username}?start=ref_{update.effective_user.id}`\n\n"
            "➖➖➖➖➖➖➖➖➖➖\n"
            "📊 **CLICK STATISTICS:**\n"
            "├ 📅 **TODAY:** 0 clicks\n"
            "├ 📅 **THIS WEEK:** 0 clicks\n"
            "├ 📅 **THIS MONTH:** 0 clicks\n"
            "└ 📈 **ALL TIME:** 0 clicks\n\n"
            "👥 **REFERRAL STATS:**\n"
            "├ 👤 **TOTAL USERS:** 0 users\n"
            "├ 📊 **CONVERSION:** 0.0%\n"
            "└ 💎 **COMMISSION RATE:** 50%\n\n"
            "➖➖➖➖➖➖➖➖➖➖\n"
            "💰 **EARNINGS:**\n"
            "├ 📅 **TODAY:** $0.00\n"
            "├ 📅 **THIS WEEK:** $0.00\n"
            "├ 📅 **THIS MONTH:** $0.00\n"
            "└ 💵 **ALL TIME:** $0.00\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        markup = InlineKeyboardMarkup([
            [
                InlineKeyboardButton("📊 Generate Stats Image", callback_data="partner_image"),
                InlineKeyboardButton("📩 Download CSV Report", callback_data="partner_csv")
            ],
            [InlineKeyboardButton("🔄 Refresh Stats", callback_data="partner_refresh")]
        ])
        await update.message.reply_text(msg, reply_markup=markup, parse_mode="Markdown")
        
    elif text == "❓ FAQ":
        await update.message.reply_text(get_faq_text(), reply_markup=get_faq_keyboard(), parse_mode="Markdown")

    elif text == "👤 PROFILE":
        msg = (
            "👤 **USER PROFILE**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "🆔 **ACCOUNT DETAILS**\n"
            f"├ 👤 **ID:** `{update.effective_user.id}`\n"
            "├ 👑 **STATUS:** Free Tier\n"
            "├ 💰 **BALANCE:** $0.00\n"
            "├ ⚡ **ACTIONS USED:** 0\n"
            "└ ⏱️ **UPTIME USED:** 0 mins\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        markup = InlineKeyboardMarkup([
            [
                InlineKeyboardButton("💰 Deposit", callback_data="profile_deposit"),
                InlineKeyboardButton("⭐ Upgrade Plan", callback_data="profile_upgrade")
            ],
            [InlineKeyboardButton("📝 Transaction History", callback_data="profile_history")]
        ])
        await update.message.reply_text(msg, reply_markup=markup, parse_mode="Markdown")

    else:
        await update.message.reply_text(f"You selected {text}. This module is currently under construction.", parse_mode="Markdown")

async def handle_inline_callbacks(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Processes clicks on inline buttons attached to messages."""
    query = update.callback_query
    
    # Acknowledge the button press
    await query.answer()

    # Partner Callbacks
    if query.data == "partner_image":
        await query.answer("🖼️ Generating image... (Requires Pillow library setup)", show_alert=True)
    elif query.data == "partner_csv":
        await query.answer("📩 CSV generation is pending database connection.", show_alert=True)
    elif query.data == "partner_refresh":
        await query.answer("🔄 Stats refreshed successfully.", show_alert=False)
    elif query.data == "trigger_payment":
        await query.answer("💳 Payment gateway is currently unlinked.", show_alert=True)
        
    # FAQ Callbacks
    elif query.data == "faq_ask":
        msg = (
            "❓ **UTILITY PANEL | ASK A QUESTION**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "❔ **ASK A QUESTION**\n"
            "📝 PLEASE TYPE YOUR QUESTION BELOW\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        markup = InlineKeyboardMarkup([[InlineKeyboardButton("❌ CANCEL", callback_data="faq_cancel")]])
        await query.message.edit_text(msg, reply_markup=markup, parse_mode="Markdown")
        
    elif query.data == "faq_cancel":
        await query.message.edit_text(get_faq_text(), reply_markup=get_faq_keyboard(), parse_mode="Markdown")
        
    elif query.data == "faq_menu":
        await query.message.delete()
        
    # Profile Callbacks
    elif query.data == "profile_deposit":
        await query.answer("💰 Deposit functionality is not yet configured.", show_alert=True)
    elif query.data == "profile_upgrade":
        await query.answer("⭐ Plan upgrade options loading...", show_alert=True)
    elif query.data == "profile_history":
        await query.answer("📝 No transaction history found.", show_alert=True)

def main() -> None:
    """Starts the application."""
    if not TOKEN:
        logger.error("BOT_TOKEN variable is missing! The bot cannot start.")
        return

    application = Application.builder().token(TOKEN).build()

    # Handlers
    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", start))
    
    # Text handler for bottom keyboard
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_menu_clicks))
    
    # Callback handler for inline buttons attached to messages
    application.add_handler(CallbackQueryHandler(handle_inline_callbacks))

    application.run_polling(allowed_updates=Update.ALL_TYPES)

if __name__ == "__main__":
    main()
