import os
import logging
from telegram import Update, KeyboardButton, ReplyKeyboardMarkup, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

# Enable logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

# Fetch Token
TOKEN = os.getenv("BOT_TOKEN")

def get_main_menu():
    """Generates the persistent bottom keyboard layout."""
    keyboard = [
        [KeyboardButton("📊 DASHBOARD")],
        [KeyboardButton("💳 PAYMENT"), KeyboardButton("⚡ FEATURES"), KeyboardButton("⚙️ SYSTEM")],
        [KeyboardButton("🖋️ SUBSCRIPTION"), KeyboardButton("🔑 ACTIVATE")],
        [KeyboardButton("❓ FAQ"), KeyboardButton("📈 RESULTS"), KeyboardButton("📋 COMMANDS")],
        [KeyboardButton("👤 PROFILE"), KeyboardButton("💬 SUPPORT"), KeyboardButton("🤝 PARTNER")]
    ]
    return ReplyKeyboardMarkup(keyboard, resize_keyboard=True, persistent=True)

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Sends the welcome message and activates the bottom keyboard."""
    user_name = update.effective_user.first_name
    
    welcome_text = (
        f"👋 **WELCOME TO UTILITY PANEL**\n"
        f"➖➖➖➖➖➖➖➖➖➖\n\n"
        f"🧠 **SYSTEM STATUS**\n"
        f"├ 🟢 **STATUS:** Operational\n"
        f"└ 📈 **UPTIME:** 100%\n\n"
        f"⚡ **WELCOME, {user_name}**\n"
        f"🛡️ **PREMIUM UTILITY SOLUTION**\n\n"
        f"👇 **TO GET STARTED, USE THE MENU BELOW**"
    )

    await update.message.reply_text(
        welcome_text, 
        reply_markup=get_main_menu(), 
        parse_mode="Markdown"
    )

async def handle_menu_clicks(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handles the text inputs generated by pressing the bottom keyboard buttons."""
    text = update.message.text

    if text == "📊 DASHBOARD":
        msg = (
            "📊 **UTILITY DASHBOARD**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "⛔ **ACCESS DENIED**\n"
            "├ 💳 **NO ACTIVE SUBSCRIPTION**\n"
            "└ 🛒 **PURCHASE A PLAN TO CONTINUE**\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        # Adds the single inline button attached to the message
        markup = InlineKeyboardMarkup([[InlineKeyboardButton("💳 PAYMENT", callback_data="trigger_payment")]])
        await update.message.reply_text(msg, reply_markup=markup, parse_mode="Markdown")

    elif text == "⚡ FEATURES":
        msg = (
            "⚡ **FEATURES**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "🧠 **SYSTEM STATUS**\n"
            "├ 🟢 **STATUS:** Operational\n"
            "└ 📈 **UPTIME:** 100%\n\n"
            "💬 **OUR UTILITY BOT IS PACKED WITH ADVANCED FEATURES!**"
        )
        await update.message.reply_text(msg, parse_mode="Markdown")

    elif text == "⚙️ SYSTEM":
        msg = (
            "⚙️ **SYSTEM STATUS**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "🖥️ **SERVER STATUS**\n"
            "├ ✅ **API:** Online\n"
            "├ ✅ **DATABASE:** Connected\n"
            "├ ✅ **SERVICES:** Operational\n"
            "└ ✅ **PAYMENTS:** Active\n\n"
            "📊 **PERFORMANCE**\n"
            "├ 📶 **UPTIME:** 99.9%\n"
            "├ ⚡ **RESPONSE:** < 100ms\n"
            "└ 🔄 **LAST CHECK:** Just now\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        await update.message.reply_text(msg, parse_mode="Markdown")

    elif text == "📈 RESULTS":
        msg = (
            "📈 **RESULTS**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "⭐ **REVIEWS & PERFORMANCE**\n"
            "├ • AUTHENTIC USER REVIEWS\n"
            "├ • SUCCESS STORIES\n"
            "├ • PERFORMANCE STATISTICS\n"
            "├ • COMMUNITY DISCUSSIONS\n"
            "└ • LATEST UPDATES\n\n"
            "🌐 **JOIN OUR COMMUNITY**\n"
            "👇 **CLICK BELOW**\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        # Adds the URL redirect button (shows the top-right arrow in Telegram)
        markup = InlineKeyboardMarkup([[InlineKeyboardButton("VIEW RESULTS ↗", url="https://github.com")]])
        await update.message.reply_text(msg, reply_markup=markup, parse_mode="Markdown")

    elif text == "📋 COMMANDS":
        msg = (
            "📋 **COMMANDS**\n"
            "🟢 **OPERATIONAL | 📈 UPTIME: 100%**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "🤖 **MAIN COMMANDS**\n"
            "◆ 📓 /help | **VIEW COMMAND LIST**\n"
            "◆ 🛒 /purchase | **PURCHASE ACCESS**"
        )
        await update.message.reply_text(msg, parse_mode="Markdown")

    elif text == "💬 SUPPORT":
        msg = (
            "💬 **SUPPORT**\n"
            "➖➖➖➖➖➖➖➖➖➖\n\n"
            "📡 **SUPPORT STATUS**\n"
            "├ 🟢 **STATUS:** Active\n"
            "└ ⏱️ **RESPONSE:** 2-6h\n\n"
            "💬 **COMMON TOPICS**\n"
            "├ • PAYMENT PROCESSING\n"
            "├ • SUBSCRIPTION ACTIVATION\n"
            "├ • BOT SUPPORT\n"
            "└ • TECHNICAL ISSUES\n\n"
            "ℹ️ **BEFORE CONTACTING**\n"
            "├ • CHECK TRANSACTION STATUS\n"
            "├ • VERIFY SUBSCRIPTION\n"
            "├ • TRY /start COMMAND\n"
            "└ • REVIEW FAQ SECTION\n\n"
            "➖➖➖➖➖➖➖➖➖➖"
        )
        # Adds the split URL redirect buttons
        markup = InlineKeyboardMarkup([
            [
                InlineKeyboardButton("💬 SUPPORT ↗", url="https://t.me/telegram"), 
                InlineKeyboardButton("📢 CHANNEL ↗", url="https://t.me/telegram")
            ]
        ])
        await update.message.reply_text(msg, reply_markup=markup, parse_mode="Markdown")
        
    else:
        # Fallback for buttons not explicitly coded yet
        await update.message.reply_text(f"You selected {text}. This module is currently under construction.", parse_mode="Markdown")

def main() -> None:
    """Starts the application."""
    if not TOKEN:
        logger.error("BOT_TOKEN variable is missing! The bot cannot start.")
        return

    application = Application.builder().token(TOKEN).build()

    # Handlers
    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", start))
    
    # This handler catches all standard text messages (which is what the bottom keyboard outputs)
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_menu_clicks))

    application.run_polling(allowed_updates=Update.ALL_TYPES)

if __name__ == "__main__":
    main()
